package sg.edu.nus.iss.server.models;

public class HospitalReview {
    
    private Integer id; // auto-generated by MySQL during insert
    private String facilityId;
    // private String facilityEthAddress; // get from MySQL
    private Integer ethReviewIndex; // return from Smart Contract
    private String reviewer; // get from jwt token
    private String patientId; 
    private boolean patientVerified;
    private Integer nurseCommunication;
    private Integer doctorCommunication;
	private Integer staffResponsiveness;
	private Integer communicationAboutMedicines;
	private Integer dischargeInformation;
	private Integer careTransition;
	private Integer cleanliness;
	private Integer quientness;
	private Integer overallRating;
	private Integer willingnessToRecommend;
    private String comments;
    
    public Integer getId() {
        return id;
    }
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFacilityId() {
        return facilityId;
    }
    public void setFacilityId(String facilityId) {
        this.facilityId = facilityId;
    }
    // public String getFacilityEthAddress() {
    //     return facilityEthAddress;
    // }
    // public void setFacilityEthAddress(String facilityEthAddress) {
    //     this.facilityEthAddress = facilityEthAddress;
    // }
    public Integer getEthReviewIndex() {
        return ethReviewIndex;
    }
    public void setEthReviewIndex(Integer ethReviewIndex) {
        this.ethReviewIndex = ethReviewIndex;
    }
    public String getReviewer() {
        return reviewer;
    }
    public void setReviewer(String reviewer) {
        this.reviewer = reviewer;
    }
    public String getPatientId() {
        return patientId;
    }
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    public boolean isPatientVerified() {
        return patientVerified;
    }
    public void setPatientVerified(boolean patientVerified) {
        this.patientVerified = patientVerified;
    }
    public Integer getNurseCommunication() {
        return nurseCommunication;
    }
    public void setNurseCommunication(Integer nurseCommunication) {
        this.nurseCommunication = nurseCommunication;
    }
    public Integer getDoctorCommunication() {
        return doctorCommunication;
    }
    public void setDoctorCommunication(Integer doctorCommunication) {
        this.doctorCommunication = doctorCommunication;
    }
    public Integer getStaffResponsiveness() {
        return staffResponsiveness;
    }
    public void setStaffResponsiveness(Integer staffResponsiveness) {
        this.staffResponsiveness = staffResponsiveness;
    }
    public Integer getCommunicationAboutMedicines() {
        return communicationAboutMedicines;
    }
    public void setCommunicationAboutMedicines(Integer communicationAboutMedicines) {
        this.communicationAboutMedicines = communicationAboutMedicines;
    }
    public Integer getDischargeInformation() {
        return dischargeInformation;
    }
    public void setDischargeInformation(Integer dischargeInformation) {
        this.dischargeInformation = dischargeInformation;
    }
    public Integer getCareTransition() {
        return careTransition;
    }
    public void setCareTransition(Integer careTransition) {
        this.careTransition = careTransition;
    }
    public Integer getCleanliness() {
        return cleanliness;
    }
    public void setCleanliness(Integer cleanliness) {
        this.cleanliness = cleanliness;
    }
    public Integer getQuientness() {
        return quientness;
    }
    public void setQuientness(Integer quientness) {
        this.quientness = quientness;
    }
    public Integer getOverallRating() {
        return overallRating;
    }
    public void setOverallRating(Integer overallRating) {
        this.overallRating = overallRating;
    }
    public Integer getWillingnessToRecommend() {
        return willingnessToRecommend;
    }
    public void setWillingnessToRecommend(Integer willingnessToRecommend) {
        this.willingnessToRecommend = willingnessToRecommend;
    }
    public String getComments() {
        return comments;
    }
    public void setComments(String comments) {
        this.comments = comments;
    }
    @Override
    public String toString() {
        return "HospitalReview [id=" + id + ", facilityId=" + facilityId + ", ethReviewIndex=" + ethReviewIndex
                + ", reviewer=" + reviewer + ", patientId=" + patientId + ", patientVerified=" + patientVerified
                + ", nurseCommunication=" + nurseCommunication + ", doctorCommunication=" + doctorCommunication
                + ", staffResponsiveness=" + staffResponsiveness + ", communicationAboutMedicines="
                + communicationAboutMedicines + ", dischargeInformation=" + dischargeInformation + ", careTransition="
                + careTransition + ", cleanliness=" + cleanliness + ", quientness=" + quientness + ", overallRating="
                + overallRating + ", willingnessToRecommend=" + willingnessToRecommend + ", comments=" + comments + "]";
    }

    
    
}
